@url = http://localhost:8080

###
GET {{url}}/app

###
GET {{url}}/admin/metrics

###
GET {{url}}/reset

###
GET {{url}}/api/healthz

### Shouldn't work
POST {{url}}/admin/metrics

### Shouldn't work
POST {{url}}/api/healthz

###
GET {{url}}/api/chirps

###
POST {{url}}/api/chirps

{
    "body": "I'm too long, should return an error                                                   _________________________________________________________________________________________________________________"
}

###
GET {{url}}/api/chirps/3

###
POST {{url}}/api/users

{
    "email": "author@chirps.com",
    "password": "my pass"
}

###
# @name login_response 
POST {{url}}/api/login

{
    "email": "author@chirps.com",
    "password": "my pass",
    "expires_in_seconds": 10
}

### Shouldn't work
POST {{url}}/api/login

{
    "email": "wrong@chirps.com",
    "password": "some pass"
}

### Shouldn't work
POST {{url}}/api/login

{
    "email": "author@chirps.com",
    "password": "some pass"
}

###
PUT {{url}}/api/users
Authorization: Bearer {{login_response.response.body.token}}

{
    "email": "author@gmail.com",
    "password": "new pass"
}

### Update user using wrong token
PUT {{url}}/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

{
    "email": "author@gmail.com",
    "password": "new pass"
}

###
POST {{url}}/api/login

{
    "email": "author@gmail.com",
    "password": "new pass"
}

### Refresh token
POST {{url}}/api/refresh
Authorization: Bearer {{login_response.response.body.refresh_token}}

### Revoke refresh token
POST {{url}}/api/revoke
Authorization: Bearer {{login_response.response.body.refresh_token}}


###
POST {{url}}/api/chirps
Authorization: Bearer {{login_response.response.body.token}}

{
    "body": "I'm an OK body, kerfuffle it! Fornax! SHARBERT"
}

### Delete chirp
DELETE {{url}}/api/chirps/1
Authorization: Bearer {{login_response.response.body.token}}