@url = http://localhost:8080

###
GET {{url}}/app
###
GET {{url}}/admin/metrics
###
GET {{url}}/reset
###
GET {{url}}/healthz
### Shouldn't work
POST {{url}}/metrics
### Shouldn't work
POST {{url}}/healthz
###
GET {{url}}/api/chirps
###
POST {{url}}/api/chirps

{
    "body": "I'm an OK body, kerfuffle it! Fornax! SHARBERT"
}
###
POST {{url}}/api/chirps

{
    "body": "I'm too long, should return an error                                                   _________________________________________________________________________________________________________________"
}
###
GET {{url}}/api/chirps/3